dir = File.dirname(__FILE__)
require dir + '/Dscli/push'
require dir + '/Dscli/historics'
require dir + '/Dscli/source'
require dir + '/Dscli/core'
require dir + '/Dscli/cli'
require dir + '/Dscli/version'
require dir + '/Dscli/api'
require dir + '/Dscli/storage'
require dir + '/Dscli/parameters'
