dir = File.dirname(__FILE__)
require dir + '/dscli/push'
require dir + '/dscli/historics'
require dir + '/dscli/source'
require dir + '/dscli/core'
require dir + '/dscli/cli'
require dir + '/dscli/version'
require dir + '/dscli/api'
require dir + '/dscli/storage'
require dir + '/dscli/parameters'
